version: "3.7"
services:
  laravel-db:
    container_name: ${APP_NAME}-laravel-db
    image: mysql:${MYSQL_VERSION:-8.0}
    restart: unless-stopped
    networks: 
      - traefik_default
    ports:
      - ${DEV_PORT_DATABASE}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: ${TZ}

  laravel:
    container_name: ${APP_NAME}-laravel
    image: xolvionl/laravel:minimal-8.0
    user: ${UID}
    command: php-fpm -F
    depends_on:
      - laravel-db
    environment:
      TZ: ${TZ}
      COMPOSER_HOME: ~/.composer
      COMPOSER_CACHE_DIR: ~/.composer/cache
    restart: unless-stopped
    working_dir: /var/www/
    networks: 
      - traefik_default
    volumes:
      - ./:/var/www
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  laravel-nginx:
    container_name: ${APP_NAME}-laravel-nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - laravel
    environment:
      - PUID=1234
      - PGID=1234
      - TZ=${TZ}
      - APP_NAME=${APP_NAME}
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/templates/
    networks: 
      - traefik_default
    labels:
      - traefik.enable=true

networks:
  traefik_default:
    external: true