version: "3.7"
services:
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:${MYSQL_VERSION:-8.0}
    restart: unless-stopped
    networks: 
      - traefik_default
    ports:
      - ${DEV_PORT_DATABASE:-10500}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: ${TZ}

  php:
    container_name: ${APP_NAME}-php
    image: xolvionl/laravel:${XOLVIO_DOCKER_TAG:-minimal-8.0}
    user: "${UID:-1000}"
    command: php-fpm -F
    hostname: ${APP_NAME}
    extra_hosts:
        - "${APP_NAME}.localhost:host-gateway"
    depends_on:
      - mysql
    environment:
      TZ: ${TZ}
      COMPOSER_HOME: ~/.composer
      COMPOSER_CACHE_DIR: ~/.composer/cache
    restart: unless-stopped
    working_dir: /var/www/
    networks: 
      - traefik_default
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    environment:
      - PUID=1234
      - PGID=1234
      - TZ=${TZ}
      - APP_NAME=${APP_NAME}
    volumes:
      - type: bind
        source: ./
        target: /var/www
      - type: bind
        source: ./nginx
        target: /etc/nginx/templates/
    networks: 
      - traefik_default
    labels:
      - traefik.enable=true

networks:
  traefik_default:
    external: true
